# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d24307acd0ac78847d12019e7d4242df824a6444a6e6a3a1775eb7a22961752be4945eb9d929717b0cde7aa1e526dffaefa00dd3b9774dfe2bd074c2089e035

test:
  secret_key_base: ed9810bb5202a1531163ce8ccb01c9ac426f7f44617451c0213188a776d099698298850def52afa2a8668f92eb5049a5b323bc56856662c0c54ae9e939725eed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
